#! /usr/bin/env bash
 
# This script is a modified version of the script located here: https://gist.github.com/Klathmon/2a8e6eb3f4a48c2768c1
# The diff statement has been modified for OSX Yosemite and I have included verbose outputs for the script to ensure output is seen correctly.
 
# The MIT License (MIT)

# Copyright (c) 2015 David Gee <david.gee@ipengineer.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 
exitcode=0

printf "\n======================"
printf "Pre-commit hook fired"
printf "======================\n"
 
for file in `git diff --cached --name-only --diff-filter=ACM | grep .go`
do

	printf "\n----------------------"
	printf "Formatting and writing..."
	printf "----------------------\n"
    printf "File is" + $file
    output=`gofmt -w "$file"`
    if test -n "$output"
    then
        echo >&2 "$output"
        exitcode=1
    fi
 
	printf "\n----------------------"
	printf "Go Tool Vetting"
	printf "----------------------\n"
    echo -n "$(tput setaf 1)"
    go tool vet "$file"
    if [ $? -ne 0 ]
    then
        exitcode=1
    fi
    echo -n "$(tput sgr0)"
 
    
	printf "\n----------------------"
	printf "GoLint-ing"
	printf "----------------------\n"
	
    echo -n "$(tput setaf 4)"
    golint "$file"
    echo -n "$(tput sgr0)"
 
    git add "$file"
done
exit $exitcode
